---
name: Update dependent repositories
on:
  push:
    branches:
      - main
jobs:
  release:
    if: ${{ github.event.commits[0].author.name != 'dependabot[bot]' }}
    uses: networkservicemesh/.github/.github/workflows/update-dependent-repositories-gomod.yaml@main
    with:
      dependent_repositories: '["cmd-forwarder-ovs"]'
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
